# Generated by Django 3.2.16 on 2023-01-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_price_subscription_result_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='service_price',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='result_price',
            new_name='price',
        ),
    ]
